### ISSUE TITLE
UI disappears when "Dev Environments" is selected 

### ISSUE THREAD

**Issue by datumflux** [docker/dev-environments#4]
**Describe the bug**
The normal screen comes out for a while, and then all UI disappears.
Occurs only when you click the "Dev Environments" menu.

**To Reproduce**
1. Dashboard open
2. Click on 'Dev Environments'
3. See error

**Expected behavior**

**Screenshots**

<img width="1272" alt="스크린샷 2021-06-25 오전 12 57 18" src="https://user-images.githubusercontent.com/40652766/123296274-77912400-d551-11eb-836d-ca32f205232d.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.4

**Additional context**

**Comment by chris-crone** [comment]
Hi @datumflux! Thanks for the report.

Can you please close the UI, reopen it and then follow the instructions here to upload a diagnostics report: https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback

Please then post the ID here

**Comment by datumflux** [comment]
B8E819BB-DC7E-429E-A067-E472381D2388/20210624164738

**Comment by gtardif** [comment]
Hi, thanks for the diagnostics. 
For some reason I think one of the devenv file has been scratched ; could you : 
`cat ~/.docker/devenvironments/data.json` 
From your logs, I suspect this contains `null` instead of json content

If this is the case; to unblock you, you can then
`rm ~/.docker/devenvironments/data.json`  
then try again to restart Docker Desktop Dashboard, hopefully you should be able to open the Dev Environments tab

We'll investigate more to see if we can find out how you ended up in this state ; possibly this is something we have fixed in the meantime, and will be shipped soon

Let us know if this helps and how this goes. Thanks for your feedback

**Comment by gtardif** [comment]
This will be fixed with the next release (hopefully shipping soon)
In the meantime `rm ~/.docker/devenvironments/data.json`  should unblock to let you getting back into Dev Environments.

**Comment by chris-crone** [comment]
Thanks for closing this @datumflux :)

This is fixed in Desktop 3.5.2 which is rolling out to users now. If anyone with this issue doesn't see an update, click the whale icon then "Check for Updates..." which will force check
